version: '3.8'

services:
    auth-api:
        container_name: auth-api
        build:
            context: .
            dockerfile: ./dockerfiles/production/Dockerfile
        image: auth-api:latest
        restart: always
        ports:
            - 8000:8000
        env_file: .env
        environment:
            APP_PORT: 8000
            MONGO_URI: mongodb://mongodb:27017/auth_db
            ACCESS_TOKEN_SECRET: fklagasdklmkdamkandasmfkmakfkajakfdsajflkdsdfsdamflkf
            REFRESH_TOKEN_SECRET: klsdfjlkaslzfjhafafhbaskfbakufbabhsdfcDJKABFASEDFBZLJH
        networks:
            - auth-api-network
        depends_on:
            - mongodb
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M

    mongodb:
        container_name: mongodb
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongodb-data:/data/db
        networks:
            - auth-api-network
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M

networks:
    auth-api-network:
        name: auth-api-network
        driver: bridge

volumes:
    mongodb-data:
        name: mongodb-data
